### ISSUE TITLE
Export selected collection hierarchy as spreadsheet

### ISSUE THREAD

**Issue by metaweidner** [uhlibraries-digital/carpenters#14]
Export selected collection hierarchy as XLSX (or CSV?), including ASpace URIs, for data entry and ingest with Carpenters 1.0

**Comment by seanlw** [comment]
Since Carpenters has grown over time and the need to have v1.0 as an option is slowly going away, is this something we still need?

**Comment by metaweidner** [comment]
Closing this as unnecessary. We can reopen if it surfaces again.
