### ISSUE TITLE
Import project directory files and place them in the selected hierarchy

### ISSUE THREAD

**Issue by metaweidner** [uhlibraries-digital/carpenters#15]
Given a project directory named in conformance with the digitization file naming scheme, import the files and associate them with the appropriate digital object in the selected hierarchy

**Comment by seanlw** [comment]
This feature should have the option to input how many files should be grouped together per item, i.e. 2 files for every item. This will also make the item level in the filename irrelevant.

**Comment by seanlw** [comment]
@ajkrewer Could there ever be more than 2 files grouped to an item?

**Comment by ajkrewer** [comment]
@seanlw   Yes, there could be more than 2 files grouped to an item, in the case of a pamphlet or a book.
