### ISSUE TITLE
Note field interoperable with Brays application

### ISSUE THREAD

**Issue by ajkrewer** [uhlibraries-digital/carpenters#18]
It would be great to have an optional note field for each individual item that could record information about copyright, pii, redaction, etc.; this info could be passed along to the dip to be read by Brays within the Brays application to aid in decision-making within the metadata unit.  Can discuss in future in-person meeting if this isn't clear.

**Comment by seanlw** [comment]
You can add the field 'productionNotes' to accomplish that. Brays understands that field and will flag the object.

Would that work?

**Comment by seanlw** [comment]
There is also 'uhlib.note'. @metaweidner would something like that work as well?

**Comment by ajkrewer** [comment]
@seanlw   I'm unfamiliar with the specific functionalities of Brays or how that note might look within the carpenter's app, since there aren't really "fields" that we work with in Carpenters.  This sounds promising, though---let's discuss in standups in the new year?

**Comment by seanlw** [comment]
For v1.0 it would be with the spreadsheet metadata. Would this be information that would benifate being listed in the finding aid as well?

We can pick this back up in the new year.

**Comment by metaweidner** [comment]
@seanlw  https://uhlibraries-digital.github.io/bcdams-map/#note is a display field for end-user descriptive data. We may need to differentiate between fields for display (public) and non-display (in-house).

**Comment by ajkrewer** [comment]
@seanlw   Also, I think the thought was that it was just a comment that would be passed to the other app... it wouldn't necessarily have to be included in the formal metadata record... you would need to ask Anne about her thoughts on that.  This functionality would essentially be a way to streamline comments from SC to the metadata unit.

**Comment by ajkrewer** [comment]
@seanlw    I was thinking in terms of v 2.0.  No need to integrate that into the old version.

**Comment by seanlw** [comment]
@ajkrewer Ok, v2.0 would be different. We can discuss this during our first Sprint planing meeting for 2017.
