### ISSUE TITLE
Ability to create ingest packages without a finding aid

### ISSUE THREAD

**Issue by seanlw** [uhlibraries-digital/carpenters#19]
As a user, not all collection will have a finding aid. I would like the ability to create objects and associate files with them which will be exported to Archivematica and Access. These collections won't have a finding aid with them and the system needs to turn off that integration with ASpace.

**Comment by librarycard** [comment]
this ability will be critical both for migration (yearbooks, newsletters, rare books/manuscripts) and for new projects (Daily Cougar)

**Comment by seanlw** [comment]
Resolved with https://github.com/uhlibraries-digital/carpenters/commit/a733ee112ec93cceae4bbd83a3574c45c435bffa
