### ISSUE TITLE
As a user I would like to handle file-level description

### ISSUE THREAD

**Issue by seanlw** [uhlibraries-digital/carpenters#21]
The ability to deal with file-level description and not just item-level description, i.e. multiple digital objects linked to one folder/archival object.

**Comment by seanlw** [comment]
I think this has been discussion and various levels of the workflow and other products. We need to have a deeper discussion about what this will do across the workflow and not just within Carpenters.

**Comment by librarycard** [comment]
it's easy to create this type of arrangement in ASpace (file-level archival object associated with many item-level digital objects) so i'm having a hard time picturing the complications, although i know there must be many, between creating artificial "items" in carpenters, file management, and lack of item-level descriptive metadata. it would be good to walk through the overall workflow to determine what the impacts of this would be. i hope that we'll be moving away from this arrangement in future projects, but it will definitely happen with migration collections.

**Comment by metaweidner** [comment]
File = ArchivesSpace Folder

**Comment by metaweidner** [comment]
Load crosswalk profile that specifies what metadata from ASpace goes where?

**Comment by metaweidner** [comment]
@librarycard This should be broken down into stories similar to the ASpace Title and Date field stories. Let me know if there are any other aspects to this that I am missing.

**Comment by metaweidner** [comment]
I'm no longer sure what this means. Will add again if it re-surfaces.
