### ISSUE TITLE
Notification Buttons

### ISSUE THREAD

**Issue by seanlw** [uhlibraries-digital/carpenters#22]
Have notification buttons to alert other users during the workflow process.

**Comment by seanlw** [comment]
I do have some concerns about this one. It always seems like a good idea, but many implementations often fail at it. I've had many experiences as people come and go where the list to notify people grow stall and often it stops being used all together. Also, as workflows change often times so does the way people communicate. Again having a notification system going unused.

**Comment by librarycard** [comment]
yes, i think we can ditch the notification feature. we're usually in contact with each other during the course of a project anyway :)
