### ISSUE TITLE
As a preservation administrator, I would prefer if the files in the right hand column disappeared as they were assigned to an item to avoid incorrectly assigning a file.

### ISSUE THREAD

**Issue by ajkrewer** [uhlibraries-digital/carpenters#31]

**Comment by seanlw** [comment]
That should be happening now, if not then this is a bug.

**Comment by ajkrewer** [comment]
Actually, after I typed this in, some of the files did start disappearing.  However, I did notice a few that I had assigned didn't disappear earlier.  If the files were in consecutive order I would be able to more closely monitor those changes.

**Comment by seanlw** [comment]
Ok, we can make sure that's happening once we address the file order bug: https://github.com/uhlibraries-digital/carpenters/issues/29

**Comment by seanlw** [comment]
Closing this since it has been tested, and the load column is being removed in future iterations.
