### ISSUE TITLE
As a preservation administrator, I would appreciate a batch load option that utilized workflow artifacts already produced by the digitization unit, to save time when undertaking large-scale file assignment.

### ISSUE THREAD

**Issue by ajkrewer** [uhlibraries-digital/carpenters#32]
I'm finding using the application more time consuming in the post-process phase, as I have to individually assign files for each item.  This would have taken maybe fifteen to thirty minutes with the spreadsheet, but assigning files manually (when the collection does have some "single" items as well as double-sided items) is going to take me hours.

**Comment by seanlw** [comment]
Is the assign feature in Carpenters not working as expected? The assign feature was created to help with assigning each file separately. Do you see that feature changing in some way?

**Comment by ajkrewer** [comment]
I was afraid to use it, frankly, because there were "single" items scattered into each area of the hierarchy, so selecting "2 files" would have resulted in incorrect assignment of files, and I was unsure how much cleanup work that would entail and thought it might be more straightforward and potentially less complicated if I had more control over the process.

**Comment by seanlw** [comment]
Sounds like we might want to rethink how that feature should be designed. Having something in Carpenters that makes you afraid to use it, isn't a feature that should be there.

**Comment by ajkrewer** [comment]
Yeah--- also, as the collections scale up in size, it would be rather difficult to manually assign files--there would be so much clicking and dragging involved, whereas some sort of import file that could be quickly created by hand (and read by the system) could do that work for me.

**Comment by ajkrewer** [comment]
We can simplify what the students are creating... they are essentially just creating a list of filenames with hard returns to indicate the next object. Could easily just use a one-column spreadsheet and not the old one, etc., since I wouldn't have to structure anything at this point.

**Comment by metaweidner** [comment]
@ajkrewer Why not have the students do the assignment in Carpenters instead of creating a list?

**Comment by ajkrewer** [comment]
@metaweidner   I will continue to stand behind my position that having the students use Carpenters would slow production and would greatly increase the time required for QC'ing a project.  I've demoed Carpenters for Crystal, so she has an idea of the tool's functionality.  You may want to consult her for more detailed, machine-specific workflow concerns during our prioritization meeting.

**Comment by metaweidner** [comment]
This issue has been superseded by recent changes in workflow design and Carpenters functionality.
