### ISSUE TITLE
When I accidentally assigned access files to the preservation file space in the archival hierarchy, the files were accepted by the program and turned purple, even though they did not have the _pm suffix to the filename.

### ISSUE THREAD

**Issue by ajkrewer** [uhlibraries-digital/carpenters#34]

**Comment by seanlw** [comment]
If you reassign the file to the correct space, does the color not change to reflect the new location?
Carpenters isn't restrictive on the filenames (except for auto-assigning) since other institutions may not have the same file naming schema.

**Comment by ajkrewer** [comment]
The files change color according to filename in the righthand column, so I was confused and thought that would carry over to the rest of the project's design.  I did not try that, but I assume that would happen (changing back to beige if I move it to access)

**Comment by seanlw** [comment]
This could be a case where color coding everywhere isn't always a good thing. I think looking at the file manager is worth investigating a re-design.

**Comment by metaweidner** [comment]
This is no longer relevant since we removed the load files interface.
