### ISSUE TITLE
As a preservation administrator, I would like to have a "rollback" function in Carpenter's 2.0 to account for any potential errors after processing.

### ISSUE THREAD

**Issue by ajkrewer** [uhlibraries-digital/carpenters#35]

**Comment by seanlw** [comment]
After an export, you can fix errors and re-export. Files will be moved again to the correct spot. You can do this over many exports. Will that satisfy the "rollback"? What other use cases might there be for this feature?

**Comment by ajkrewer** [comment]
As long as it can understand changes and reorder everything to reflect those changes, that's all that matters.  Other use cases could potentially arise in the future, but I don't see any for now.

**Comment by seanlw** [comment]
It should be understanding changes. Worth further testing to make sure of that.

**Comment by ajkrewer** [comment]
We might end up doing that with the current collection after I get back from vacation (given there will be some changes/corrections for sure), or Anne or Bethany could feel free to test it out if you need to move forward quickly.

**Comment by metaweidner** [comment]
Transferred to Trello as 'copy files on export' story.
