### ISSUE TITLE
As a preservation administrator, I would like to have the functionality of using the control and shift buttons to select ranges of files or specific files, so that I can save time by dragging multiple files at once.

### ISSUE THREAD

**Issue by ajkrewer** [uhlibraries-digital/carpenters#49]

**Comment by ajkrewer** [comment]
Just realized you could do that via the add files button, but it would be nice to have directly in the app.  Nice to have, but not essential.

**Comment by metaweidner** [comment]
This is no longer relevant since we removed the load files interface.
