### ISSUE TITLE
When I had three items left, each with 32 files, the program split one group of access & preservation files across two access objects and started the first half of the second Montrose voice issue in the third access space.

### ISSUE THREAD

**Issue by ajkrewer** [uhlibraries-digital/carpenters#50]
I will say it looked like the program tripped up due to an excel file I also have in the same directory.

**Comment by ajkrewer** [comment]
![capture](https://user-images.githubusercontent.com/20687464/28378243-2b8abd26-6c75-11e7-87ce-994d19cf42d7.JPG)

**Comment by seanlw** [comment]
Invalid since the filenames were missing `_pm` to classify the image as a preservation file during auto assign.
