### ISSUE TITLE
Auto Assign Does Not Recognize Pages

### ISSUE THREAD

**Issue by metaweidner** [uhlibraries-digital/carpenters#59]
Auto Assign Files function does not recognize pages as a level within the archival hierarchy.
![carpentersautoassignpagesbug](https://user-images.githubusercontent.com/7347746/31355631-bea9b1f4-ad00-11e7-845d-6f62e7378fa3.PNG)

**Comment by seanlw** [comment]
Isn't really a bug. Carpenters only recognizes these container types:

b: 'Box',
c: 'Cabinet',
d: 'Drawer',
f: 'Folder',
i: 'Item',
t: 'Tube'

If a new type `page` is needed then this will be a added feature.

**Comment by metaweidner** [comment]
@seanlw The app won't let me assign any more files after those error messages. That seems like a bug.

**Comment by seanlw** [comment]
@metaweidner that's the correct behavior since it can't find the correct location because of the unknown type. Carpenters won't guess at where to put it.

**Comment by seanlw** [comment]
`Page` seems to be a new container

**Comment by metaweidner** [comment]
@seanlw I loaded the images and attempted to auto-assign. It gave me those messages. Now I can't drag any of the files from the built in assignment window or the windows file viewer. The app is completely frozen. Had to end the task from the task manager.

**Comment by seanlw** [comment]
That sounds like a different issue than the auto assignment error. It just got triggered during that event.

**Comment by metaweidner** [comment]
This issue is no longer relevant since we removed the load files interface.
